# =============================================================================
# DEFAULT IT CONFIGURATION VALUES
# =============================================================================
DEFAULT_NUMBER_OF_SOCKETS_PER_SERVER = 2
DEFAULT_CPU_PRICE_PER_UNIT = 2400
DEFAULT_TOTAL_CHANNELS = 16
DEFAULT_DIMM_CAPACITY_IN_GB = 96
DEFAULT_DIMM_COST_PER_GB = 4
DEFAULT_NETWORK_CABLE_COST_PER_SERVER = 100.0
DEFAULT_SERVERS_PER_RACK = 14
DEFAULT_SWITCH_COST_PER_UNIT = 8000
DEFAULT_HPC_AI_COST_PER_SERVER = 50000
DEFAULT_25_SERVER_L2_BOM = 1200
DEFAULT_DDRS_6400_CHANNELS = 12
