services:

  frontend:
    build: .
    container_name: novazure-frontend
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    ports:
      - 3000:3000
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: novazure-backend
    ports:
      - 8000:8000
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: novazure-nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge