services:

  frontend:
    image: 290767212636.dkr.ecr.eu-west-2.amazonaws.com/novazure-frontend:latest
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    ports:
      - 3000:3000
    networks:
      - app-network

  backend:
    image: 290767212636.dkr.ecr.eu-west-2.amazonaws.com/novazure-backend:latest
    ports:
      - 8000:8000
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge