export const countryCodeOptions = [
	{ value: "+1", label: "+1 (US/Canada)" },
	{ value: "+44", label: "+44 (UK)" },
	{ value: "+33", label: "+33 (France)" },
	{ value: "+49", label: "+49 (Germany)" },
	{ value: "+39", label: "+39 (Italy)" },
	{ value: "+34", label: "+34 (Spain)" },
	{ value: "+31", label: "+31 (Netherlands)" },
	{ value: "+32", label: "+32 (Belgium)" },
	{ value: "+41", label: "+41 (Switzerland)" },
	{ value: "+43", label: "+43 (Austria)" },
	{ value: "+46", label: "+46 (Sweden)" },
	{ value: "+47", label: "+47 (Norway)" },
	{ value: "+45", label: "+45 (Denmark)" },
	{ value: "+358", label: "+358 (Finland)" },
	{ value: "+48", label: "+48 (Poland)" },
	{ value: "+420", label: "+420 (Czech Republic)" },
	{ value: "+36", label: "+36 (Hungary)" },
	{ value: "+380", label: "+380 (Ukraine)" },
	{ value: "+7", label: "+7 (Russia)" },
	{ value: "+81", label: "+81 (Japan)" },
	{ value: "+82", label: "+82 (South Korea)" },
	{ value: "+86", label: "+86 (China)" },
	{ value: "+91", label: "+91 (India)" },
	{ value: "+61", label: "+61 (Australia)" },
	{ value: "+64", label: "+64 (New Zealand)" },
	{ value: "+55", label: "+55 (Brazil)" },
	{ value: "+54", label: "+54 (Argentina)" },
	{ value: "+56", label: "+56 (Chile)" },
	{ value: "+57", label: "+57 (Colombia)" },
	{ value: "+58", label: "+58 (Venezuela)" },
	{ value: "+52", label: "+52 (Mexico)" },
	{ value: "+51", label: "+51 (Peru)" },
	{ value: "+593", label: "+593 (Ecuador)" },
	{ value: "+595", label: "+595 (Paraguay)" },
	{ value: "+598", label: "+598 (Uruguay)" },
	{ value: "+591", label: "+591 (Bolivia)" },
	{ value: "+27", label: "+27 (South Africa)" },
	{ value: "+234", label: "+234 (Nigeria)" },
	{ value: "+254", label: "+254 (Kenya)" },
	{ value: "+20", label: "+20 (Egypt)" },
	{ value: "+212", label: "+212 (Morocco)" },
	{ value: "+216", label: "+216 (Tunisia)" },
	{ value: "+213", label: "+213 (Algeria)" },
	{ value: "+971", label: "+971 (UAE)" },
	{ value: "+966", label: "+966 (Saudi Arabia)" },
	{ value: "+974", label: "+974 (Qatar)" },
	{ value: "+973", label: "+973 (Bahrain)" },
	{ value: "+965", label: "+965 (Kuwait)" },
	{ value: "+968", label: "+968 (Oman)" },
	{ value: "+972", label: "+972 (Israel)" },
	{ value: "+90", label: "+90 (Turkey)" },
	{ value: "+98", label: "+98 (Iran)" },
	{ value: "+964", label: "+964 (Iraq)" },
	{ value: "+962", label: "+962 (Jordan)" },
	{ value: "+961", label: "+961 (Lebanon)" },
	{ value: "+963", label: "+963 (Syria)" },
	{ value: "+967", label: "+967 (Yemen)" },
	{ value: "+249", label: "+249 (Sudan)" },
	{ value: "+251", label: "+251 (Ethiopia)" },
	{ value: "+255", label: "+255 (Tanzania)" },
	{ value: "+256", label: "+256 (Uganda)" },
	{ value: "+233", label: "+233 (Ghana)" },
	{ value: "+225", label: "+225 (Ivory Coast)" },
	{ value: "+237", label: "+237 (Cameroon)" },
	{ value: "+221", label: "+221 (Senegal)" },
	{ value: "+224", label: "+224 (Guinea)" },
	{ value: "+226", label: "+226 (Burkina Faso)" },
	{ value: "+227", label: "+227 (Niger)" },
	{ value: "+228", label: "+228 (Togo)" },
	{ value: "+229", label: "+229 (Benin)" },
	{ value: "+230", label: "+230 (Mauritius)" },
	{ value: "+231", label: "+231 (Liberia)" },
	{ value: "+232", label: "+232 (Sierra Leone)" },
	{ value: "+235", label: "+235 (Chad)" },
	{ value: "+236", label: "+236 (Central African Republic)" },
	{ value: "+238", label: "+238 (Cape Verde)" },
	{ value: "+239", label: "+239 (São Tomé and Príncipe)" },
	{ value: "+240", label: "+240 (Equatorial Guinea)" },
	{ value: "+241", label: "+241 (Gabon)" },
	{ value: "+242", label: "+242 (Republic of the Congo)" },
	{ value: "+243", label: "+243 (Democratic Republic of the Congo)" },
	{ value: "+244", label: "+244 (Angola)" },
	{ value: "+245", label: "+245 (Guinea-Bissau)" },
	{ value: "+246", label: "+246 (British Indian Ocean Territory)" },
	{ value: "+247", label: "+247 (Ascension Island)" },
	{ value: "+248", label: "+248 (Seychelles)" },
	{ value: "+250", label: "+250 (Rwanda)" },
	{ value: "+252", label: "+252 (Somalia)" },
	{ value: "+253", label: "+253 (Djibouti)" },
	{ value: "+257", label: "+257 (Burundi)" },
	{ value: "+258", label: "+258 (Mozambique)" },
	{ value: "+259", label: "+259 (Zanzibar)" },
	{ value: "+260", label: "+260 (Zambia)" },
	{ value: "+261", label: "+261 (Madagascar)" },
	{ value: "+262", label: "+262 (Réunion)" },
	{ value: "+263", label: "+263 (Zimbabwe)" },
	{ value: "+264", label: "+264 (Namibia)" },
	{ value: "+265", label: "+265 (Malawi)" },
	{ value: "+266", label: "+266 (Lesotho)" },
	{ value: "+267", label: "+267 (Botswana)" },
	{ value: "+268", label: "+268 (Eswatini)" },
	{ value: "+269", label: "+269 (Comoros)" },
	{ value: "+290", label: "+290 (Saint Helena)" },
	{ value: "+291", label: "+291 (Eritrea)" },
	{ value: "+297", label: "+297 (Aruba)" },
	{ value: "+298", label: "+298 (Faroe Islands)" },
	{ value: "+299", label: "+299 (Greenland)" },
	{ value: "+350", label: "+350 (Gibraltar)" },
	{ value: "+351", label: "+351 (Portugal)" },
	{ value: "+352", label: "+352 (Luxembourg)" },
	{ value: "+353", label: "+353 (Ireland)" },
	{ value: "+354", label: "+354 (Iceland)" },
	{ value: "+355", label: "+355 (Albania)" },
	{ value: "+356", label: "+356 (Malta)" },
	{ value: "+357", label: "+357 (Cyprus)" },
	{ value: "+359", label: "+359 (Bulgaria)" },
	{ value: "+370", label: "+370 (Lithuania)" },
	{ value: "+371", label: "+371 (Latvia)" },
	{ value: "+372", label: "+372 (Estonia)" },
	{ value: "+373", label: "+373 (Moldova)" },
	{ value: "+374", label: "+374 (Armenia)" },
	{ value: "+375", label: "+375 (Belarus)" },
	{ value: "+376", label: "+376 (Andorra)" },
	{ value: "+377", label: "+377 (Monaco)" },
	{ value: "+378", label: "+378 (San Marino)" },
	{ value: "+379", label: "+379 (Vatican City)" },
	{ value: "+381", label: "+381 (Serbia)" },
	{ value: "+382", label: "+382 (Montenegro)" },
	{ value: "+383", label: "+383 (Kosovo)" },
	{ value: "+385", label: "+385 (Croatia)" },
	{ value: "+386", label: "+386 (Slovenia)" },
	{ value: "+387", label: "+387 (Bosnia and Herzegovina)" },
	{ value: "+389", label: "+389 (North Macedonia)" },
	{ value: "+421", label: "+421 (Slovakia)" },
	{ value: "+423", label: "+423 (Liechtenstein)" },
	{ value: "+500", label: "+500 (Falkland Islands)" },
	{ value: "+501", label: "+501 (Belize)" },
	{ value: "+502", label: "+502 (Guatemala)" },
	{ value: "+503", label: "+503 (El Salvador)" },
	{ value: "+504", label: "+504 (Honduras)" },
	{ value: "+505", label: "+505 (Nicaragua)" },
	{ value: "+506", label: "+506 (Costa Rica)" },
	{ value: "+507", label: "+507 (Panama)" },
	{ value: "+508", label: "+508 (Saint Pierre and Miquelon)" },
	{ value: "+509", label: "+509 (Haiti)" },
	{ value: "+590", label: "+590 (Guadeloupe)" },
	{ value: "+592", label: "+592 (Guyana)" },
	{ value: "+594", label: "+594 (French Guiana)" },
	{ value: "+596", label: "+596 (Martinique)" },
	{ value: "+597", label: "+597 (Suriname)" },
	{ value: "+599", label: "+599 (Netherlands Antilles)" },
	{ value: "+670", label: "+670 (East Timor)" },
	{ value: "+672", label: "+672 (Australian External Territories)" },
	{ value: "+673", label: "+673 (Brunei)" },
	{ value: "+674", label: "+674 (Nauru)" },
	{ value: "+675", label: "+675 (Papua New Guinea)" },
	{ value: "+676", label: "+676 (Tonga)" },
	{ value: "+677", label: "+677 (Solomon Islands)" },
	{ value: "+678", label: "+678 (Vanuatu)" },
	{ value: "+679", label: "+679 (Fiji)" },
	{ value: "+680", label: "+680 (Palau)" },
	{ value: "+681", label: "+681 (Wallis and Futuna)" },
	{ value: "+682", label: "+682 (Cook Islands)" },
	{ value: "+683", label: "+683 (Niue)" },
	{ value: "+685", label: "+685 (Samoa)" },
	{ value: "+686", label: "+686 (Kiribati)" },
	{ value: "+687", label: "+687 (New Caledonia)" },
	{ value: "+688", label: "+688 (Tuvalu)" },
	{ value: "+689", label: "+689 (French Polynesia)" },
	{ value: "+690", label: "+690 (Tokelau)" },
	{ value: "+691", label: "+691 (Micronesia)" },
	{ value: "+692", label: "+692 (Marshall Islands)" },
	{ value: "+850", label: "+850 (North Korea)" },
	{ value: "+852", label: "+852 (Hong Kong)" },
	{ value: "+853", label: "+853 (Macau)" },
	{ value: "+855", label: "+855 (Cambodia)" },
	{ value: "+856", label: "+856 (Laos)" },
	{ value: "+880", label: "+880 (Bangladesh)" },
	{ value: "+886", label: "+886 (Taiwan)" },
	{ value: "+960", label: "+960 (Maldives)" },
	{ value: "+970", label: "+970 (Palestine)" },
	{ value: "+975", label: "+975 (Bhutan)" },
	{ value: "+976", label: "+976 (Mongolia)" },
	{ value: "+977", label: "+977 (Nepal)" },
	{ value: "+992", label: "+992 (Tajikistan)" },
	{ value: "+993", label: "+993 (Turkmenistan)" },
	{ value: "+994", label: "+994 (Azerbaijan)" },
	{ value: "+995", label: "+995 (Georgia)" },
	{ value: "+996", label: "+996 (Kyrgyzstan)" },
	{ value: "+998", label: "+998 (Uzbekistan)" },
];

export const countryOptions = [
	{ value: "US", label: "United States" },
	{ value: "CA", label: "Canada" },
	{ value: "GB", label: "United Kingdom" },
	{ value: "FR", label: "France" },
	{ value: "DE", label: "Germany" },
	{ value: "IT", label: "Italy" },
	{ value: "ES", label: "Spain" },
	{ value: "NL", label: "Netherlands" },
	{ value: "BE", label: "Belgium" },
	{ value: "CH", label: "Switzerland" },
	{ value: "AT", label: "Austria" },
	{ value: "SE", label: "Sweden" },
	{ value: "NO", label: "Norway" },
	{ value: "DK", label: "Denmark" },
	{ value: "FI", label: "Finland" },
	{ value: "PL", label: "Poland" },
	{ value: "CZ", label: "Czech Republic" },
	{ value: "HU", label: "Hungary" },
	{ value: "UA", label: "Ukraine" },
	{ value: "RU", label: "Russia" },
	{ value: "JP", label: "Japan" },
	{ value: "KR", label: "South Korea" },
	{ value: "CN", label: "China" },
	{ value: "IN", label: "India" },
	{ value: "AU", label: "Australia" },
	{ value: "NZ", label: "New Zealand" },
	{ value: "BR", label: "Brazil" },
	{ value: "AR", label: "Argentina" },
	{ value: "CL", label: "Chile" },
	{ value: "CO", label: "Colombia" },
	{ value: "VE", label: "Venezuela" },
	{ value: "MX", label: "Mexico" },
	{ value: "PE", label: "Peru" },
	{ value: "EC", label: "Ecuador" },
	{ value: "PY", label: "Paraguay" },
	{ value: "UY", label: "Uruguay" },
	{ value: "BO", label: "Bolivia" },
	{ value: "ZA", label: "South Africa" },
	{ value: "NG", label: "Nigeria" },
	{ value: "KE", label: "Kenya" },
	{ value: "EG", label: "Egypt" },
	{ value: "MA", label: "Morocco" },
	{ value: "TN", label: "Tunisia" },
	{ value: "DZ", label: "Algeria" },
	{ value: "AE", label: "United Arab Emirates" },
	{ value: "SA", label: "Saudi Arabia" },
	{ value: "QA", label: "Qatar" },
	{ value: "BH", label: "Bahrain" },
	{ value: "KW", label: "Kuwait" },
	{ value: "OM", label: "Oman" },
	{ value: "IL", label: "Israel" },
	{ value: "TR", label: "Turkey" },
	{ value: "IR", label: "Iran" },
	{ value: "IQ", label: "Iraq" },
	{ value: "JO", label: "Jordan" },
	{ value: "LB", label: "Lebanon" },
	{ value: "SY", label: "Syria" },
	{ value: "YE", label: "Yemen" },
	{ value: "SD", label: "Sudan" },
	{ value: "ET", label: "Ethiopia" },
	{ value: "TZ", label: "Tanzania" },
	{ value: "UG", label: "Uganda" },
	{ value: "GH", label: "Ghana" },
	{ value: "CI", label: "Ivory Coast" },
	{ value: "CM", label: "Cameroon" },
	{ value: "SN", label: "Senegal" },
	{ value: "GN", label: "Guinea" },
	{ value: "BF", label: "Burkina Faso" },
	{ value: "NE", label: "Niger" },
	{ value: "TG", label: "Togo" },
	{ value: "BJ", label: "Benin" },
	{ value: "MU", label: "Mauritius" },
	{ value: "LR", label: "Liberia" },
	{ value: "SL", label: "Sierra Leone" },
	{ value: "TD", label: "Chad" },
	{ value: "CF", label: "Central African Republic" },
	{ value: "CV", label: "Cape Verde" },
	{ value: "ST", label: "São Tomé and Príncipe" },
	{ value: "GQ", label: "Equatorial Guinea" },
	{ value: "GA", label: "Gabon" },
	{ value: "CG", label: "Republic of the Congo" },
	{ value: "CD", label: "Democratic Republic of the Congo" },
	{ value: "AO", label: "Angola" },
	{ value: "GW", label: "Guinea-Bissau" },
	{ value: "IO", label: "British Indian Ocean Territory" },
	{ value: "AC", label: "Ascension Island" },
	{ value: "SC", label: "Seychelles" },
	{ value: "RW", label: "Rwanda" },
	{ value: "SO", label: "Somalia" },
	{ value: "DJ", label: "Djibouti" },
	{ value: "BI", label: "Burundi" },
	{ value: "MZ", label: "Mozambique" },
	{ value: "ZM", label: "Zambia" },
	{ value: "MG", label: "Madagascar" },
	{ value: "RE", label: "Réunion" },
	{ value: "ZW", label: "Zimbabwe" },
	{ value: "NA", label: "Namibia" },
	{ value: "MW", label: "Malawi" },
	{ value: "LS", label: "Lesotho" },
	{ value: "BW", label: "Botswana" },
	{ value: "SZ", label: "Eswatini" },
	{ value: "KM", label: "Comoros" },
	{ value: "SH", label: "Saint Helena" },
	{ value: "ER", label: "Eritrea" },
	{ value: "AW", label: "Aruba" },
	{ value: "FO", label: "Faroe Islands" },
	{ value: "GL", label: "Greenland" },
	{ value: "GI", label: "Gibraltar" },
	{ value: "PT", label: "Portugal" },
	{ value: "LU", label: "Luxembourg" },
	{ value: "IE", label: "Ireland" },
	{ value: "IS", label: "Iceland" },
	{ value: "AL", label: "Albania" },
	{ value: "MT", label: "Malta" },
	{ value: "CY", label: "Cyprus" },
	{ value: "BG", label: "Bulgaria" },
	{ value: "LT", label: "Lithuania" },
	{ value: "LV", label: "Latvia" },
	{ value: "EE", label: "Estonia" },
	{ value: "MD", label: "Moldova" },
	{ value: "AM", label: "Armenia" },
	{ value: "BY", label: "Belarus" },
	{ value: "AD", label: "Andorra" },
	{ value: "MC", label: "Monaco" },
	{ value: "SM", label: "San Marino" },
	{ value: "VA", label: "Vatican City" },
	{ value: "RS", label: "Serbia" },
	{ value: "ME", label: "Montenegro" },
	{ value: "XK", label: "Kosovo" },
	{ value: "HR", label: "Croatia" },
	{ value: "SI", label: "Slovenia" },
	{ value: "BA", label: "Bosnia and Herzegovina" },
	{ value: "MK", label: "North Macedonia" },
	{ value: "SK", label: "Slovakia" },
	{ value: "LI", label: "Liechtenstein" },
	{ value: "FK", label: "Falkland Islands" },
	{ value: "BZ", label: "Belize" },
	{ value: "GT", label: "Guatemala" },
	{ value: "SV", label: "El Salvador" },
	{ value: "HN", label: "Honduras" },
	{ value: "NI", label: "Nicaragua" },
	{ value: "CR", label: "Costa Rica" },
	{ value: "PA", label: "Panama" },
	{ value: "PM", label: "Saint Pierre and Miquelon" },
	{ value: "HT", label: "Haiti" },
	{ value: "GP", label: "Guadeloupe" },
	{ value: "GY", label: "Guyana" },
	{ value: "GF", label: "French Guiana" },
	{ value: "MQ", label: "Martinique" },
	{ value: "SR", label: "Suriname" },
	{ value: "AN", label: "Netherlands Antilles" },
	{ value: "TL", label: "East Timor" },
	{ value: "CX", label: "Christmas Island" },
	{ value: "CC", label: "Cocos Islands" },
	{ value: "NF", label: "Norfolk Island" },
	{ value: "BN", label: "Brunei" },
	{ value: "NR", label: "Nauru" },
	{ value: "PG", label: "Papua New Guinea" },
	{ value: "TO", label: "Tonga" },
	{ value: "SB", label: "Solomon Islands" },
	{ value: "VU", label: "Vanuatu" },
	{ value: "FJ", label: "Fiji" },
	{ value: "PW", label: "Palau" },
	{ value: "WF", label: "Wallis and Futuna" },
	{ value: "CK", label: "Cook Islands" },
	{ value: "NU", label: "Niue" },
	{ value: "WS", label: "Samoa" },
	{ value: "KI", label: "Kiribati" },
	{ value: "NC", label: "New Caledonia" },
	{ value: "TV", label: "Tuvalu" },
	{ value: "PF", label: "French Polynesia" },
	{ value: "TK", label: "Tokelau" },
	{ value: "FM", label: "Micronesia" },
	{ value: "MH", label: "Marshall Islands" },
	{ value: "KP", label: "North Korea" },
	{ value: "HK", label: "Hong Kong" },
	{ value: "MO", label: "Macau" },
	{ value: "KH", label: "Cambodia" },
	{ value: "LA", label: "Laos" },
	{ value: "BD", label: "Bangladesh" },
	{ value: "TW", label: "Taiwan" },
	{ value: "MV", label: "Maldives" },
	{ value: "PS", label: "Palestine" },
	{ value: "BT", label: "Bhutan" },
	{ value: "MN", label: "Mongolia" },
	{ value: "NP", label: "Nepal" },
	{ value: "TJ", label: "Tajikistan" },
	{ value: "TM", label: "Turkmenistan" },
	{ value: "AZ", label: "Azerbaijan" },
	{ value: "GE", label: "Georgia" },
	{ value: "KG", label: "Kyrgyzstan" },
	{ value: "UZ", label: "Uzbekistan" },
];
