import { Droplets, Wind, Thermometer } from "lucide-react";

export interface Product {
	id: string;
	name: string;
	description: string;
	model: string;
	category: string;
	efficiency: string;
	specifications: {
		powerRating: string;
		coolingCapacity: string;
		dimensions: string;
		weight: string;
		operatingTemperature: string;
		certifications: string;
	};
	features: string[];
	status: "pending" | "verified" | "active";
	parameterCount: number;
	calculationOverview: string;
}

export interface Solution {
	id: string;
	name: string;
	description: string;
	category: string;
	logo: React.ComponentType<{ className?: string }>;
	products: Product[];
	status: "pending" | "verified" | "active";
	parameterCount: number;
	calculationOverview: string;
}

export interface SolutionType {
	id: string;
	name: string;
	description: string;
	icon: React.ComponentType<{ className?: string }>;
	variants: SolutionVariant[];
}

export interface SolutionVariant {
	id: string;
	name: string;
	description: string;
	icon: React.ComponentType<{ className?: string }>;
}

export interface Parameter {
	id: string;
	name: string;
	value: string;
	test_value: string;
	unit: string;
	description: string;
	provided_by: string;
	input_type: string;
	output: boolean;
	level: string;
	category: {
		name: string;
		color: string;
	};
}

export interface Calculation {
	id: string;
	name: string;
	formula: string;
	result: number | string;
	units: string;
	description: string;
	status: "valid" | "error" | "pending";
	category: "financial" | "performance" | "efficiency" | "operational";
}

// Default calculations for solution configuration
export const defaultCalculations: Calculation[] = [
	{
		id: "total-capex",
		name: "Total CAPEX",
		formula: "equipment_cost + installation_cost + commissioning_cost",
		result: 140000.0,
		units: "$",
		description: "Total Capital Expenditure for the system",
		status: "valid",
		category: "financial",
	},
	{
		id: "annual-opex",
		name: "Annual OPEX",
		formula: "annual_energy_cost + annual_maintenance_cost + annual_labor_cost",
		result: 142000.0,
		units: "$/year",
		description: "Annual Operating Expenditure",
		status: "valid",
		category: "financial",
	},
	{
		id: "five-year-tco",
		name: "5-Year TCO",
		formula: "total_capex + (annual_opex * 5)",
		result: 850000.0,
		units: "$",
		description: "Total Cost of Ownership over 5 years",
		status: "valid",
		category: "financial",
	},
	{
		id: "payback-period",
		name: "Payback Period",
		formula: "total_capex / annual_savings",
		result: 1.87,
		units: "years",
		description: "Time to recover initial investment",
		status: "valid",
		category: "financial",
	},
	{
		id: "overall-efficiency",
		name: "Overall Efficiency",
		formula: "cooling_load / power_consumption * 100",
		result: "Error",
		units: "%",
		description: "Overall system efficiency percentage",
		status: "error",
		category: "efficiency",
	},
	{
		id: "capacity-utilization",
		name: "Capacity Utilization",
		formula: "cooling_load / unit_capacity * 100",
		result: "Error",
		units: "%",
		description: "How much of rated capacity is being used",
		status: "error",
		category: "performance",
	},
	{
		id: "throughput-rate",
		name: "Throughput Rate",
		formula: "cooling_load / operating_hours",
		result: "Error",
		units: "units/hr",
		description: "Rate of processing or production",
		status: "error",
		category: "operational",
	},
	{
		id: "availability-factor",
		name: "Availability Factor",
		formula: "operating_hours / 8760 * 100",
		result: "Error",
		units: "%",
		description: "System availability percentage",
		status: "error",
		category: "operational",
	},
	{
		id: "power-density",
		name: "Power Density",
		formula: "power_consumption / facility_size",
		result: "Error",
		units: "kW/m²",
		description: "Power consumption per unit area",
		status: "error",
		category: "performance",
	},
	{
		id: "cooling-efficiency",
		name: "Cooling Efficiency",
		formula: "cooling_load / power_consumption",
		result: "Error",
		units: "kW/kW",
		description: "Cooling delivered per unit power consumed",
		status: "error",
		category: "efficiency",
	},
];

// Default parameters for solution configuration
// export const defaultParameters2: Parameter[] = [
// 	// L1 - Facility Level Parameters
// 	{
// 		id: "facility-size",
// 		level: "L1",
// 		name: "Facility Size",
// 		defaultValue: 1000,
// 		overrideValue: null,
// 		units: "m²",
// 		description: "Total facility floor area",
// 		category: "operational",
// 	},
// 	{
// 		id: "operating-hours",
// 		level: "L1",
// 		name: "Operating Hours",
// 		defaultValue: 24,
// 		overrideValue: null,
// 		units: "hours/day",
// 		description: "Daily operational hours",
// 		category: "operational",
// 	},
// 	{
// 		id: "equipment-cost",
// 		level: "L1",
// 		name: "Equipment Cost",
// 		defaultValue: 100000,
// 		overrideValue: null,
// 		units: "$",
// 		description: "Initial cost of equipment and hardware",
// 		category: "cost",
// 	},
// 	{
// 		id: "installation-cost",
// 		level: "L1",
// 		name: "Installation Cost",
// 		defaultValue: 25000,
// 		overrideValue: null,
// 		units: "$",
// 		description: "Cost of installation and setup",
// 		category: "cost",
// 	},
// 	{
// 		id: "commissioning-cost",
// 		level: "L1",
// 		name: "Commissioning Cost",
// 		defaultValue: 15000,
// 		overrideValue: null,
// 		units: "$",
// 		description: "Cost of testing and commissioning",
// 		category: "cost",
// 	},
// 	{
// 		id: "annual-energy-cost",
// 		level: "L1",
// 		name: "Annual Energy Cost",
// 		defaultValue: 50000,
// 		overrideValue: null,
// 		units: "$/year",
// 		description: "Annual electricity and energy costs",
// 		category: "cost",
// 	},
// 	{
// 		id: "annual-maintenance-cost",
// 		level: "L1",
// 		name: "Annual Maintenance Cost",
// 		defaultValue: 12000,
// 		overrideValue: null,
// 		units: "$/year",
// 		description: "Annual maintenance and servicing costs",
// 		category: "cost",
// 	},
// 	{
// 		id: "annual-labor-cost",
// 		level: "L1",
// 		name: "Annual Labor Cost",
// 		defaultValue: 80000,
// 		overrideValue: null,
// 		units: "$/year",
// 		description: "Annual operational labor costs",
// 		category: "cost",
// 	},
// 	{
// 		id: "annual-savings",
// 		level: "L1",
// 		name: "Annual Savings",
// 		defaultValue: 75000,
// 		overrideValue: null,
// 		units: "$/year",
// 		description: "Annual cost savings from the system",
// 		category: "cost",
// 	},

// 	// L2 - System Level Parameters
// 	{
// 		id: "cooling-load",
// 		level: "L2",
// 		name: "Cooling Load",
// 		defaultValue: 500,
// 		overrideValue: null,
// 		units: "kW",
// 		description: "Total heat load to be removed",
// 		category: "performance",
// 	},
// 	{
// 		id: "temperature-setpoint",
// 		level: "L2",
// 		name: "Temperature Setpoint",
// 		defaultValue: 22,
// 		overrideValue: null,
// 		units: "°C",
// 		description: "Target temperature for cooling system",
// 		category: "performance",
// 	},
// 	{
// 		id: "humidity-setpoint",
// 		level: "L2",
// 		name: "Humidity Setpoint",
// 		defaultValue: 45,
// 		overrideValue: null,
// 		units: "%RH",
// 		description: "Target relative humidity",
// 		category: "performance",
// 	},

// 	// L3 - Component Level Parameters
// 	{
// 		id: "air-flow-rate",
// 		level: "L3",
// 		name: "Air Flow Rate",
// 		defaultValue: 1200,
// 		overrideValue: null,
// 		units: "m³/min",
// 		description: "Required air circulation rate",
// 		category: "performance",
// 	},
// 	{
// 		id: "supply-air-temperature",
// 		level: "L3",
// 		name: "Supply Air Temperature",
// 		defaultValue: 18,
// 		overrideValue: null,
// 		units: "°C",
// 		description: "Temperature of air supplied to space",
// 		category: "performance",
// 	},
// 	{
// 		id: "delta-t",
// 		level: "L3",
// 		name: "Delta T",
// 		defaultValue: 8,
// 		overrideValue: null,
// 		units: "K",
// 		description: "Temperature difference between supply and return air",
// 		category: "performance",
// 	},

// 	// L4 - Unit Level Parameters
// 	{
// 		id: "unit-capacity",
// 		level: "L4",
// 		name: "Unit Capacity",
// 		defaultValue: 25,
// 		overrideValue: null,
// 		units: "kW",
// 		description: "Cooling capacity per unit",
// 		category: "performance",
// 	},
// 	{
// 		id: "number-of-units",
// 		level: "L4",
// 		name: "Number of Units",
// 		defaultValue: 20,
// 		overrideValue: null,
// 		units: "units",
// 		description: "Total number of cooling units",
// 		category: "operational",
// 	},
// 	{
// 		id: "power-consumption",
// 		level: "L4",
// 		name: "Power Consumption",
// 		defaultValue: 8,
// 		overrideValue: null,
// 		units: "kW",
// 		description: "Electrical power consumption per unit",
// 		category: "performance",
// 	},
// 	{
// 		id: "number-of-servers",
// 		level: "L4",
// 		name: "Number of Servers",
// 		defaultValue: 1000,
// 		overrideValue: null,
// 		units: "servers",
// 		description: "Total number of servers",
// 		category: "operational",
// 	},
// 	{
// 		id: "server-power-consumption",
// 		level: "L4",
// 		name: "Server Power Consumption",
// 		defaultValue: 1,
// 		overrideValue: null,
// 		units: "kW",
// 		description: "Power consumption per server",
// 		category: "performance",
// 	},
// 	{
// 		id: "server-cooling-load",
// 		level: "L4",
// 		name: "Server Cooling Load",
// 		defaultValue: 1,
// 		overrideValue: null,
// 		units: "kW",
// 		description: "Cooling load per server",
// 		category: "performance",
// 	},
// ];

// Mock data for Parameter Management System
// 10 parameters for each category: CAPEX, OPEX, Global, Data Center Industry, Liquid Cooling, Maintenance

export const defaultParameters: Parameter[] = [
	{
		id: "capex-001",
		name: "Server Hardware Cost",
		level: "L1",
		value: "5000",
		test_value: "4500",
		unit: "GBP",
		description:
			"Cost per server unit including CPU, RAM, storage, and motherboard",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-002",
		name: "Cooling Infrastructure Cost",
		level: "L1",
		value: "150000",
		test_value: "140000",
		unit: "GBP",
		description: "Initial investment for liquid cooling system installation",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-003",
		name: "Power Distribution Unit Cost",
		level: "L1",
		value: "25000",
		test_value: "23000",
		unit: "GBP",
		description: "Cost of PDU installation and electrical infrastructure",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-004",
		name: "Rack Infrastructure Cost",
		level: "L1",
		value: "8000",
		test_value: "7500",
		unit: "GBP",
		description:
			"Cost per rack including mounting hardware and cable management",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-005",
		name: "Network Equipment Cost",
		level: "L1",
		value: "35000",
		test_value: "32000",
		unit: "GBP",
		description: "Switches, routers, and network cabling infrastructure",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-006",
		name: "Facility Construction Cost",
		level: "L1",
		value: "500000",
		test_value: "480000",
		unit: "GBP",
		description: "Building construction and preparation costs per data center",
		provided_by: "company",
		input_type: "advanced",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-007",
		name: "Backup Power System Cost",
		level: "L1",
		value: "75000",
		test_value: "70000",
		unit: "GBP",
		description: "UPS and generator systems for power redundancy",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-008",
		name: "Monitoring System Cost",
		level: "L1",
		value: "20000",
		test_value: "18000",
		unit: "GBP",
		description: "Environmental monitoring and management systems",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-009",
		name: "Fire Suppression System Cost",
		level: "L1",
		value: "30000",
		test_value: "28000",
		unit: "GBP",
		description: "Fire detection and suppression system installation",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},
	{
		id: "capex-010",
		name: "Security System Cost",
		level: "L1",
		value: "15000",
		test_value: "14000",
		unit: "GBP",
		description: "Access control, cameras, and security infrastructure",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "CAPEX",
			color: "red",
		},
	},

	// OPEX Parameters (10)
	{
		id: "opex-001",
		name: "Annual Electricity Cost",
		level: "L1",
		value: "120000",
		test_value: "115000",
		unit: "GBP/year",
		description: "Annual electricity consumption costs for servers and cooling",
		provided_by: "company",
		input_type: "simple",
		output: true,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-002",
		name: "Staff Salary Cost",
		level: "L1",
		value: "45000",
		test_value: "43000",
		unit: "GBP/year",
		description: "Average annual salary per data center technician",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-003",
		name: "Insurance Premium",
		level: "L1",
		value: "8000",
		test_value: "7500",
		unit: "GBP/year",
		description: "Annual insurance premium for data center operations",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-004",
		name: "Facility Rent Cost",
		level: "L1",
		value: "25000",
		test_value: "24000",
		unit: "GBP/month",
		description: "Monthly facility rental or lease costs",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-005",
		name: "Internet Connectivity Cost",
		level: "L1",
		value: "3000",
		test_value: "2800",
		unit: "GBP/month",
		description: "Monthly cost for internet and network connectivity",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-006",
		name: "Software License Cost",
		level: "L1",
		value: "15000",
		test_value: "14000",
		unit: "GBP/year",
		description: "Annual software licensing costs for management tools",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-007",
		name: "Compliance Audit Cost",
		level: "L1",
		value: "5000",
		test_value: "4500",
		unit: "GBP/year",
		description: "Annual compliance and certification audit costs",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-008",
		name: "Waste Disposal Cost",
		level: "L1",
		value: "2000",
		test_value: "1800",
		unit: "GBP/year",
		description: "Annual electronic waste disposal and recycling costs",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-009",
		name: "Training Cost",
		level: "L1",
		value: "3000",
		test_value: "2700",
		unit: "GBP/year",
		description: "Annual staff training and certification costs",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},
	{
		id: "opex-010",
		name: "Consumables Cost",
		level: "L1",
		value: "1500",
		test_value: "1400",
		unit: "GBP/year",
		description: "Annual cost for cleaning supplies, filters, and consumables",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "OPEX",
			color: "blue",
		},
	},

	// Global Parameters (10)
	{
		id: "global-001",
		name: "UK Electricity Price",
		level: "L1",
		value: "0.28",
		test_value: "0.25",
		unit: "GBP/kWh",
		description: "UK industrial electricity price per kilowatt hour",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-002",
		name: "UK Water Cost",
		level: "L1",
		value: "3.20",
		test_value: "3.00",
		unit: "GBP/m³",
		description: "UK industrial water supply cost per cubic meter",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-003",
		name: "CO2 Emission Factor",
		level: "L1",
		value: "0.193",
		test_value: "0.180",
		unit: "kg CO2/kWh",
		description: "UK grid CO2 emission factor per kilowatt hour",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-004",
		name: "Centimeter to Meter Conversion",
		level: "L1",
		value: "0.01",
		test_value: "0.01",
		unit: "m/cm",
		description: "Conversion factor from centimeters to meters",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-005",
		name: "VAT Rate",
		level: "L1",
		value: "0.20",
		test_value: "0.20",
		unit: "ratio",
		description: "UK Value Added Tax rate for calculations",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-006",
		name: "Inflation Rate",
		level: "L1",
		value: "0.025",
		test_value: "0.03",
		unit: "ratio/year",
		description: "Annual inflation rate for cost projections",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-007",
		name: "GBP to USD Exchange Rate",
		level: "L1",
		value: "1.27",
		test_value: "1.25",
		unit: "USD/GBP",
		description: "Current exchange rate from British Pounds to US Dollars",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-008",
		name: "Working Days per Year",
		level: "L1",
		value: "252",
		test_value: "252",
		unit: "days",
		description: "Standard working days per year for operational calculations",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-009",
		name: "Hours per Day",
		level: "L1",
		value: "24",
		test_value: "24",
		unit: "hours",
		description: "Hours per day for continuous operations",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-010",
		name: "Watts to Kilowatts Conversion",
		level: "L1",
		value: "0.001",
		test_value: "0.001",
		unit: "kW/W",
		description: "Conversion factor from watts to kilowatts",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},

	// Data Center Industry Parameters (10)
	{
		id: "datacenter-001",
		name: "Server Power Consumption",
		level: "L1",
		value: "400",
		test_value: "380",
		unit: "W",
		description: "Average power consumption per server under normal load",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-002",
		name: "Power Usage Effectiveness",
		level: "L1",
		value: "1.4",
		test_value: "1.3",
		unit: "ratio",
		description: "PUE ratio for data center energy efficiency measurement",
		provided_by: "company",
		input_type: "simple",
		output: true,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-003",
		name: "Rack Density",
		level: "L1",
		value: "42",
		test_value: "40",
		unit: "U",
		description: "Number of rack units (U) per standard rack",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-004",
		name: "Server Utilization Rate",
		level: "L1",
		value: "",
		test_value: "0.70",
		unit: "ratio",
		description: "Average server utilization rate for capacity planning",
		provided_by: "user",
		input_type: "advanced",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-005",
		name: "Cooling Efficiency Ratio",
		level: "L1",
		value: "2.5",
		test_value: "2.8",
		unit: "ratio",
		description: "Cooling efficiency ratio for HVAC systems",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-006",
		name: "Network Equipment Power",
		level: "L1",
		value: "150",
		test_value: "140",
		unit: "W/port",
		description: "Average power consumption per network port",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-007",
		name: "Redundancy Factor",
		level: "L1",
		value: "1.5",
		test_value: "1.6",
		unit: "ratio",
		description: "Redundancy factor for critical systems sizing",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-008",
		name: "Uptime Requirement",
		level: "L1",
		value: "",
		test_value: "99.95",
		unit: "percentage",
		description: "Target uptime percentage for SLA compliance",
		provided_by: "user",
		input_type: "advanced",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-009",
		name: "Floor Space per Rack",
		level: "L1",
		value: "4.5",
		test_value: "4.2",
		unit: "m²",
		description: "Floor space required per rack including clearances",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},
	{
		id: "datacenter-010",
		name: "Ambient Temperature",
		level: "L1",
		value: "",
		test_value: "20",
		unit: "°C",
		description: "Target ambient temperature for optimal server operation",
		provided_by: "user",
		input_type: "simple",
		output: false,
		category: {
			name: "Data Center Industry",
			color: "purple",
		},
	},

	// Liquid Cooling Parameters (10)
	{
		id: "liquidcooling-001",
		name: "Coolant Flow Rate",
		level: "L1",
		value: "15",
		test_value: "12",
		unit: "L/min",
		description: "Coolant flow rate per server for optimal heat transfer",
		provided_by: "company",
		input_type: "advanced",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-002",
		name: "Coolant Temperature Delta",
		level: "L1",
		value: "10",
		test_value: "8",
		unit: "°C",
		description: "Temperature difference between inlet and outlet coolant",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-003",
		name: "Pump Power Consumption",
		level: "L1",
		value: "250",
		test_value: "220",
		unit: "W",
		description: "Power consumption of coolant circulation pump",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-004",
		name: "Heat Exchanger Efficiency",
		level: "L1",
		value: "0.85",
		test_value: "0.88",
		unit: "ratio",
		description: "Efficiency of liquid-to-air heat exchanger",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-005",
		name: "Coolant Specific Heat",
		level: "L1",
		value: "4.18",
		test_value: "4.20",
		unit: "kJ/kg·K",
		description: "Specific heat capacity of water-based coolant",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-006",
		name: "Coolant Density",
		level: "L1",
		value: "1000",
		test_value: "995",
		unit: "kg/m³",
		description: "Density of water-based coolant at operating temperature",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-007",
		name: "Pipe Diameter",
		level: "L1",
		value: "25",
		test_value: "20",
		unit: "mm",
		description: "Internal diameter of coolant distribution pipes",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-008",
		name: "System Pressure",
		level: "L1",
		value: "2.5",
		test_value: "2.8",
		unit: "bar",
		description: "Operating pressure of liquid cooling system",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-009",
		name: "Coolant pH Level",
		level: "L1",
		value: "7.5",
		test_value: "7.2",
		unit: "pH",
		description: "pH level of coolant for corrosion prevention",
		provided_by: "company",
		input_type: "advanced",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},
	{
		id: "liquidcooling-010",
		name: "Thermal Resistance",
		level: "L1",
		value: "0.1",
		test_value: "0.08",
		unit: "K/W",
		description: "Thermal resistance of CPU cold plate interface",
		provided_by: "company",
		input_type: "advanced",
		output: false,
		category: {
			name: "Liquid Cooling",
			color: "cyan",
		},
	},

	// Maintenance Parameters (10)
	{
		id: "maintenance-001",
		name: "Filter Replacement Frequency",
		level: "L1",
		value: "90",
		test_value: "60",
		unit: "days",
		description: "Frequency of air filter replacement in cooling systems",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-002",
		name: "Coolant Replacement Interval",
		level: "L1",
		value: "365",
		test_value: "300",
		unit: "days",
		description: "Interval for complete coolant system replacement",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-003",
		name: "Preventive Maintenance Cost",
		level: "L1",
		value: "500",
		test_value: "450",
		unit: "GBP/visit",
		description: "Cost per preventive maintenance visit",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-004",
		name: "Server Lifecycle",
		level: "L1",
		value: "5",
		test_value: "4",
		unit: "years",
		description: "Expected lifecycle of server hardware before replacement",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-005",
		name: "Pump Maintenance Interval",
		level: "L1",
		value: "180",
		test_value: "150",
		unit: "days",
		description: "Maintenance interval for coolant circulation pumps",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-006",
		name: "Emergency Repair Cost",
		level: "L1",
		value: "2000",
		test_value: "1800",
		unit: "GBP/incident",
		description: "Average cost per emergency repair incident",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-007",
		name: "Spare Parts Inventory",
		level: "L1",
		value: "15000",
		test_value: "12000",
		unit: "GBP",
		description: "Value of spare parts inventory to maintain",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-008",
		name: "Cleaning Frequency",
		level: "L1",
		value: "30",
		test_value: "21",
		unit: "days",
		description: "Frequency of equipment cleaning and inspection",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-009",
		name: "Calibration Interval",
		level: "L1",
		value: "365",
		test_value: "180",
		unit: "days",
		description: "Calibration interval for monitoring equipment",
		provided_by: "company",
		input_type: "simple",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
	{
		id: "maintenance-010",
		name: "Maintenance Staff Hours",
		level: "L1",
		value: "",
		test_value: "35",
		unit: "hours/week",
		description: "Weekly maintenance staff hours required",
		provided_by: "user",
		input_type: "advanced",
		output: false,
		category: {
			name: "Maintenance",
			color: "orange",
		},
	},
];

// Global Parameters Only - Constants and conversion factors
export const globalParameters = [
	{
		id: "global-001",
		level: "L1",
		name: "UK Electricity Price",
		value: "0.28",
		test_value: "0.28",
		unit: "GBP/kWh",
		description: "UK industrial electricity price per kilowatt hour",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-002",
		level: "L1",
		name: "UK Water Cost",
		value: "3.2",
		test_value: "3.2",
		unit: "GBP/m³",
		description: "UK industrial water supply cost per cubic meter",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-003",
		level: "L1",
		name: "CO2 Emission Factor",
		value: "0.193",
		test_value: "0.193",
		unit: "kg CO2/kWh",
		description: "UK grid CO2 emission factor per kilowatt hour",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-004",
		level: "L1",
		name: "Centimeter to Meter Conversion",
		value: "0.01",
		test_value: "0.01",
		unit: "m/cm",
		description: "Conversion factor from centimeters to meters",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-005",
		level: "L1",
		name: "VAT Rate",
		value: "0.2",
		test_value: "0.2",
		unit: "ratio",
		description: "UK Value Added Tax rate for calculations",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-006",
		level: "L1",
		name: "Inflation Rate",
		value: "0.025",
		test_value: "0.025",
		unit: "ratio/year",
		description: "Annual inflation rate for cost projections",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-007",
		level: "L1",
		name: "GBP to USD Exchange Rate",
		value: "1.27",
		test_value: "1.27",
		unit: "USD/GBP",
		description: "Current exchange rate from British Pounds to US Dollars",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-008",
		level: "L1",
		name: "Working Days per Year",
		value: "252",
		test_value: "252",
		unit: "days",
		description: "Standard working days per year for operational calculations",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-009",
		level: "L1",
		name: "Hours per Day",
		value: "24",
		test_value: "24",
		unit: "hours",
		description: "Hours per day for continuous operations",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
	{
		id: "global-010",
		level: "L1",
		name: "Watts to Kilowatts Conversion",
		value: "0.001",
		test_value: "0.001",
		unit: "kW/W",
		description: "Conversion factor from watts to kilowatts",
		provided_by: "global",
		input_type: "simple",
		output: false,
		category: {
			name: "Global",
			color: "green",
		},
	},
];

// Custom categories array to match the mock data
export const customCategories = [
	"CAPEX",
	"OPEX",
	"Global",
	"Data Center Industry",
	"Liquid Cooling",
	"Maintenance",
];

// Mock data for solution types and variants
export const solutionTypes: SolutionType[] = [
	{
		id: "air-cooling",
		name: "Air Cooling",
		description:
			"Traditional air-based cooling solutions for data center environments",
		icon: Wind,
		variants: [
			{
				id: "crac-units",
				name: "CRAC Units",
				description:
					"Computer Room Air Conditioning units for precision cooling",
				icon: Thermometer,
			},
			{
				id: "crah-units",
				name: "CRAH Units",
				description:
					"Computer Room Air Handler units for efficient air management",
				icon: Wind,
			},
			{
				id: "in-row-cooling",
				name: "In-Row Cooling",
				description: "Cooling systems positioned between server racks",
				icon: Thermometer,
			},
			{
				id: "free-cooling",
				name: "Free Cooling",
				description: "Energy-efficient cooling using ambient air temperature",
				icon: Wind,
			},
		],
	},
	{
		id: "liquid-cooling",
		name: "Liquid Cooling",
		description:
			"Advanced liquid-based cooling solutions for high-density computing",
		icon: Droplets,
		variants: [
			{
				id: "immersion-cooling",
				name: "Immersion Cooling",
				description: "Direct immersion of hardware in dielectric fluid",
				icon: Droplets,
			},
			{
				id: "direct-to-chip",
				name: "Direct-to-Chip",
				description: "Precision cooling directly to processor components",
				icon: Thermometer,
			},
			{
				id: "rear-door-heat-exchangers",
				name: "Rear Door Heat Exchangers",
				description: "Heat exchangers mounted on rack rear doors",
				icon: Thermometer,
			},
			{
				id: "liquid-cooled-racks",
				name: "Liquid Cooled Racks",
				description: "Complete rack systems with integrated liquid cooling",
				icon: Droplets,
			},
		],
	},
	{
		id: "hybrid-cooling",
		name: "Hybrid Cooling",
		description:
			"Combined air and liquid cooling systems for optimal efficiency",
		icon: Thermometer,
		variants: [
			{
				id: "hybrid-air-liquid",
				name: "Hybrid Air-Liquid",
				description: "Combined air and liquid cooling in single system",
				icon: Thermometer,
			},
			{
				id: "adaptive-cooling",
				name: "Adaptive Cooling",
				description: "Intelligent systems that switch between cooling methods",
				icon: Wind,
			},
			{
				id: "thermal-management",
				name: "Thermal Management",
				description: "Comprehensive thermal management and monitoring",
				icon: Thermometer,
			},
			{
				id: "orchestrated-cooling",
				name: "Orchestrated Cooling",
				description: "AI-driven cooling orchestration systems",
				icon: Thermometer,
			},
		],
	},
];

export const mockSolutions: Solution[] = [
	{
		id: "chassis-immersion-cooling",
		name: "Chassis Immersion Cooling",
		description:
			"Advanced single-phase immersion cooling solution for high-density data center applications with superior thermal performance and energy efficiency.",
		category: "Liquid Cooling",
		logo: Droplets,
		status: "verified",
		parameterCount: 24,
		calculationOverview:
			"Thermal resistance, heat transfer coefficient, flow rate optimization",
		products: [
			{
				id: "ku-l2-immersion",
				name: "KU:L2 Immersion System",
				description:
					"High-performance single-phase immersion cooling system designed for 2U server configurations with intelligent thermal management.",
				model: "KU:L2-IS-2000",
				category: "Immersion Cooling",
				efficiency: "PUE 1.02",
				specifications: {
					powerRating: "2kW per chassis",
					coolingCapacity: "2.5kW thermal",
					dimensions: "482x89x800mm",
					weight: "45kg",
					operatingTemperature: "15-35°C",
					certifications: "UL, CE, RoHS",
				},
				features: [
					"Single-phase dielectric fluid",
					"Intelligent thermal monitoring",
					"Automatic leak detection",
					"Modular design for scalability",
					"Remote management interface",
					"Energy-efficient pump system",
					"Silent operation",
					"Easy maintenance access",
				],
				status: "verified",
				parameterCount: 18,
				calculationOverview:
					"Heat transfer efficiency, fluid dynamics, thermal resistance mapping",
			},
			{
				id: "ku-l4-immersion",
				name: "KU:L4 Immersion System",
				description:
					"Advanced 4U immersion cooling solution for high-density computing with enhanced thermal performance and modular architecture.",
				model: "KU:L4-IS-4000",
				category: "Immersion Cooling",
				efficiency: "PUE 1.015",
				specifications: {
					powerRating: "4kW per chassis",
					coolingCapacity: "5kW thermal",
					dimensions: "482x178x800mm",
					weight: "78kg",
					operatingTemperature: "15-35°C",
					certifications: "UL, CE, RoHS, IEC 60950",
				},
				features: [
					"Enhanced thermal conductivity",
					"Multi-zone temperature control",
					"Advanced fluid management",
					"Predictive maintenance alerts",
					"Scalable rack integration",
					"Energy optimization algorithms",
					"Comprehensive monitoring suite",
					"Quick deployment capability",
				],
				status: "verified",
				parameterCount: 22,
				calculationOverview:
					"Multi-zone thermal analysis, fluid flow optimization, heat dissipation modeling",
			},
		],
	},
	{
		id: "air-cooling-systems",
		name: "Air Cooling Systems",
		description:
			"Intelligent air-based cooling solutions for traditional data center environments with advanced airflow management and energy optimization.",
		category: "Air Cooling",
		logo: Wind,
		status: "active",
		parameterCount: 19,
		calculationOverview:
			"Airflow dynamics, temperature distribution, energy consumption analysis",
		products: [
			{
				id: "airflow-pro-hvac",
				name: "AirFlow Pro HVAC",
				description:
					"High-efficiency air conditioning system with intelligent airflow management and energy optimization for data center applications.",
				model: "AFP-HVAC-5000",
				category: "Air Conditioning",
				efficiency: "PUE 1.08",
				specifications: {
					powerRating: "5kW",
					coolingCapacity: "15kW",
					dimensions: "1200x800x2000mm",
					weight: "320kg",
					operatingTemperature: "10-45°C",
					certifications: "AHRI, UL, CE",
				},
				features: [
					"Variable speed compressors",
					"Intelligent airflow control",
					"Energy recovery systems",
					"Remote monitoring capability",
					"Predictive maintenance",
					"Multi-zone temperature control",
					"Humidity management",
					"Eco-friendly refrigerants",
				],
				status: "active",
				parameterCount: 16,
				calculationOverview:
					"Airflow optimization, temperature gradient analysis, energy efficiency modeling",
			},
			{
				id: "free-cooling-eco",
				name: "Free Cooling ECO",
				description:
					"Energy-efficient free cooling system that leverages ambient air temperature for data center cooling with minimal energy consumption.",
				model: "FCE-ECO-3000",
				category: "Free Cooling",
				efficiency: "PUE 1.03",
				specifications: {
					powerRating: "3kW",
					coolingCapacity: "12kW",
					dimensions: "1000x600x1800mm",
					weight: "280kg",
					operatingTemperature: "-10-35°C",
					certifications: "UL, CE, Energy Star",
				},
				features: [
					"Ambient air utilization",
					"Intelligent temperature control",
					"Energy-efficient operation",
					"Automatic mode switching",
					"Advanced filtration systems",
					"Real-time efficiency monitoring",
					"Weather-responsive operation",
					"Low maintenance design",
				],
				status: "active",
				parameterCount: 14,
				calculationOverview:
					"Ambient temperature analysis, energy savings calculation, operational efficiency metrics",
			},
		],
	},
	{
		id: "thermal-management-suite",
		name: "Thermal Management Suite",
		description:
			"Comprehensive thermal management solution combining liquid and air cooling technologies with intelligent orchestration for optimal performance.",
		category: "Hybrid Cooling",
		logo: Thermometer,
		status: "pending",
		parameterCount: 31,
		calculationOverview:
			"Hybrid cooling optimization, thermal load balancing, energy efficiency modeling",
		products: [
			{
				id: "thermal-orchestrator-pro",
				name: "Thermal Orchestrator Pro",
				description:
					"Advanced thermal management system that intelligently coordinates liquid and air cooling for maximum efficiency and reliability.",
				model: "TOP-HYBRID-6000",
				category: "Hybrid Cooling",
				efficiency: "PUE 1.025",
				specifications: {
					powerRating: "6kW",
					coolingCapacity: "20kW",
					dimensions: "1500x1000x2200mm",
					weight: "450kg",
					operatingTemperature: "5-40°C",
					certifications: "UL, CE, ISO 9001",
				},
				features: [
					"Intelligent load balancing",
					"Dynamic cooling orchestration",
					"Real-time thermal mapping",
					"Predictive analytics",
					"Energy optimization algorithms",
					"Fault-tolerant operation",
					"Comprehensive monitoring",
					"Automated maintenance scheduling",
				],
				status: "pending",
				parameterCount: 25,
				calculationOverview:
					"Thermal load distribution, cooling efficiency optimization, energy consumption analysis",
			},
			{
				id: "eco-thermal-controller",
				name: "Eco Thermal Controller",
				description:
					"Smart thermal controller that optimizes cooling strategies based on workload, ambient conditions, and energy costs.",
				model: "ETC-SMART-4000",
				category: "Thermal Control",
				efficiency: "PUE 1.035",
				specifications: {
					powerRating: "4kW",
					coolingCapacity: "16kW",
					dimensions: "1200x800x2000mm",
					weight: "380kg",
					operatingTemperature: "10-45°C",
					certifications: "UL, CE, IEC 61508",
				},
				features: [
					"AI-powered optimization",
					"Workload-aware cooling",
					"Cost-based decision making",
					"Real-time efficiency tracking",
					"Predictive maintenance",
					"Multi-zone coordination",
					"Energy cost optimization",
					"Comprehensive reporting",
				],
				status: "pending",
				parameterCount: 28,
				calculationOverview:
					"AI-driven optimization, cost-benefit analysis, thermal efficiency modeling",
			},
		],
	},
];
