name: linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          cd backend
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run linting
        run: |
          cd backend
          source .venv/bin/activate
          ruff check .
          ruff format --check .
          ruff check --fix .


  lint-frontend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install dependencies
          run: |
            npm install
        - name: Run linting
          run: |
            npm run build